// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUf4D3PPAjOo6yaLsF-WQV6AeDexBgl7o',
    appId: '1:477583309592:android:dc509ba5cf100bea047c6d',
    messagingSenderId: '477583309592',
    projectId: 'forex-journal-app',
    storageBucket: 'forex-journal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjj5_-zTDgaaRq1TjG8AzkNjtGmDsv9Lg',
    appId: '1:477583309592:ios:320d7ed2ff9be6a4047c6d',
    messagingSenderId: '477583309592',
    projectId: 'forex-journal-app',
    storageBucket: 'forex-journal-app.firebasestorage.app',
    iosBundleId: 'com.example.forexJournalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjj5_-zTDgaaRq1TjG8AzkNjtGmDsv9Lg',
    appId: '1:477583309592:ios:320d7ed2ff9be6a4047c6d',
    messagingSenderId: '477583309592',
    projectId: 'forex-journal-app',
    storageBucket: 'forex-journal-app.firebasestorage.app',
    iosBundleId: 'com.example.forexJournalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIK7fJnJqbk9SVfGot5z0Qa4uIGvC9gow',
    appId: '1:477583309592:web:bcaf7ce2616b5077047c6d',
    messagingSenderId: '477583309592',
    projectId: 'forex-journal-app',
    authDomain: 'forex-journal-app.firebaseapp.com',
    storageBucket: 'forex-journal-app.firebasestorage.app',
    measurementId: 'G-V56CP47XGP',
  );
}
