# Calea: ios/Podfile

# Setează versiunea minimă necesară pentru pachetele Firebase și Flutter
platform :ios, '16.0'

flutter_application_path = '../..'
load File.join(flutter_application_path, '.flutter-plugins')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Includem pod-urile esențiale și cele din Flutter
  use_modular_headers!
  
  # Aici vin toate pachetele. CocoaPods le va găsi automat.
  flutter_install_all_ios_pods flutter_application_path
end