platform :ios, '16.0'

flutter_application_path = '../..'
load File.join(flutter_application_path, '.flutter-plugins')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # ADĂUGĂ LINIA ASTA:
  install_optional_flags(true)
  
  flutter_install_all_ios_pods flutter_application_path
  
  # Aici adăugăm forțarea (dacă nu există deja)
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end